import { defineConfig } from "vitepress";

export default defineConfig({
  title: "书Book",
  titleTemplate: "📚",
  description: "一生所读，尽皆于此",
  lang: "zh",
  head: [["link", { rel: "icon", href: "/favicon.svg" }]],
  cleanUrls: true,
  srcDir: "src",
  lastUpdated: true,
  sitemap: {
    hostname: "https://read.tianheg.org",
  },
  metaChunk: true,

  themeConfig: {
    outline: [2, 3],
    search: {
      provider: "local",
    },
    nav: [
      { text: "Book", link: "/" },
      { text: "Non-book", link: "/non-book/", activeMatch: "/non-book/" },
    ],
    sidebar: {
      "/": [
        { text: "RESTful Best Practices", link: "/restful-best-practices" },
        { text: "Refactoring UI", link: "/refactoring-ui" },
        {
          text: "Resilient web design",
          link: "/resilient-web-design",
          score: "3",
        },
        { text: "亲爱的三毛", link: "/qinaide-sanmao" },
        {
          text: "CSS: The Definitive Guide",
          link: "/css-the-definitive-guide",
        },
        { text: "被讨厌的勇气", link: "/courage-to-be-disliked" },
        { text: "蒙田全集", link: "/complete-works-of-montaigne" },
        {
          text: "美学、心理学和宗教信仰的演讲与对话集(1938—1946)",
          link: "/lectures-and-conversations-on-aesthetics-psychology-and-religious-belief",
        },
        { text: "吉米-哈利索引", link: "/james-herriot" },
        { text: "你是你吃出来的", link: "/ni-shini-chichulai-de", score: "5" },
        { text: "格（杂志）", link: "/ge-magazine", score: "1" },
        { text: "癌症密码", link: "/cancer-code", score: "5" },
        { text: "MAKE：独立创客手册", link: "/make-the-indie-maker-handbook" },
        { text: "狼书Node.js", link: "/langshu-nodejs" },
        { text: "面纱", link: "/the-painted-veil" },
        { text: "月亮与六便士", link: "/the-moon-and-sixpence" },
        { text: "红楼梦", link: "/honglou-meng" },
        { text: "学会如何学习", link: "/learning-how-to-learn" },
        { text: "人的自我寻求", link: "/mans-search-for-himself" },
        { text: "幸福的方法", link: "/happier" },
        { text: "芒格之道", link: "/tao-of-munger" },
        { text: "穷查理宝典", link: "/poor-charlies-almanack" },
        { text: "玄幻小说", link: "/xuanhuan" },
        { text: "哑舍", link: "/yashe" },
        { text: "狂热分子", link: "/true-believer" },
        { text: "操作系统概念", link: "/operating-system-concepts" },
        { text: "操作系统导论", link: "/operating-system-three-easy-pieces" },
        { text: "文化苦旅", link: "/wenhua-kulv" },
        { text: "挽救计划", link: "/project-hail-mary" },
        { text: "小偷家族", link: "/shoplifters" },
        { text: "献给阿尔吉侬的花束", link: "/flowers-for-algernon" },
        { text: "只是为了好玩", link: "/just-for-fun" },
        { text: "索拉里斯星", link: "/solaris" },
        { text: "以鸟兽之名", link: "/yiniaoshou-zhi-ming" },
        { text: "寂寞的游戏", link: "/jimo-de-youxi" },
        { text: "钢铁是怎样炼成的", link: "/how-the-steel-was-tempered" },
        { text: "心理学与生活", link: "/psychology-and-life" },
        { text: "哲学的故事", link: "/story-of-philosophy" },
        { text: "CSS设计的禅意", link: "/the-zen-of-css-design" },
        { text: "窗边的小豆豆", link: "/chuangbian-de-xiaodoudou" },
        { text: "张春桥：1949及以后", link: "/zhang-chunqiao-1949-jiyihou" },
        {
          text: "高效能人士的七个习惯",
          link: "/the-7-habits-of-highly-effective-people",
        },
        { text: "阿西莫夫索引", link: "/asimov" },
        { text: "如何阅读一本书", link: "/how-to-read-a-book" },
        { text: "史蒂夫·乔布斯传", link: "/steve-jobs" },
        { text: "黑客与画家", link: "/hackers-and-painters" },
        { text: "如何成为一名程序员", link: "/how-to-be-a-programmer" },
        { text: "谈美", link: "/tan-mei" },
        { text: "那些忧伤的年轻人", link: "/naxie-youshangde-nianqingren" },
        { text: "查拉图斯特拉如是说", link: "/thus-spoke-zarathustra" },
        { text: "社会心理学", link: "/social-psychology-book" },
        { text: "神曲", link: "/divine-comedy" },
        { text: "道德经", link: "/dao-de-jing" },
        { text: "借我一生", link: "/jiewo-yisheng" },
        { text: "心经", link: "/xinjing" },
        { text: "SICP(JS ver.)", link: "/sicpjs" },
        { text: "醉步男", link: "/zui-bu-nan" },
        { text: "看海的人", link: "/kanhaide-ren" },
        { text: "朝花夕拾", link: "/zhaohua-xishi" },
        { text: "人性的枷锁", link: "/of-human-bondage", score: "2" },
        { text: "刀锋", link: "/the-razors-edge", score: "2" },
        { text: "图解HTTP", link: "/tujie-http" },
        { text: "寻欢作乐", link: "/cakes-and-ale" },
        { text: "爱你就像爱生命", link: "/aini-jiuxiang-aishengming" },
        { text: "天生有罪", link: "/born-a-crime" },
        {
          text: "Web开发JS专业指南",
          link: "/professional-javascript-for-web-developers",
        },
        { text: "读书随想录", link: "/the-summing-up" },
        { text: "雪崩", link: "/snow-crash" },
        { text: "极简个性心理学", link: "/making-sence-of-people" },
        { text: "牧羊少年奇幻之旅", link: "/o-alquimista" },
        { text: "爱因斯坦自述", link: "/einstein-himself" },
        { text: "克拉拉与太阳", link: "/klara-and-the-sun" },
        { text: "什锦拼盘", link: "/shijin-pinpan" },
        { text: "拉多之星", link: "/la-duo-zhi-xing" },
        {
          text: "我生有涯愿无尽：梁漱溟自述文录",
          link: "/wo-shengyouya-yuanwujin",
        },
        { text: "时间之书", link: "/shijian-zhi-shu" },
        { text: "未来世界的幸存者", link: "/weilai-shijie-de-xingcunzhe" },
        { text: "三体", link: "/santi" },
        { text: "程序员修炼之道", link: "/the-pragmatic-programmer" },
        { text: "一九八四", link: "/nineteen-eighty-four" },
        { text: "看见", link: "/kanjian" },
        { text: "不迷茫手册", link: "/bumimang-shouce" },
        { text: "恍惚人间", link: "/huanghu-renjian" },
        { text: "过于喧嚣的孤独", link: "/too-loud-a-solitude" },
        { text: "你的第一本哲学书", link: "/what-does-it-all-mean" },
        { text: "遥远的救世主", link: "/yaoyuande-jiushizhu" },
      ],
      "/non-book/": [{ text: "笔记", link: "/non-book/" }],
    },
  },
});
