import { defineConfig } from "vitepress"

export default defineConfig({
  title: "书Book",
  titleTemplate: "📚",
  description: "一生所读，尽皆于此",
  lang: "zh-CN",
  head: [
    ["link", { rel: "icon", href: "/favicon.svg" }],
    ["script", { async: "", src: "https://wa.tianheg.org/script.js", "data-website-id": "ca63440b-f131-42eb-a62a-d07ae9563b71" }]
  ],
  cleanUrls: true,
  srcDir: "books",
  lastUpdated: true,
  sitemap: {
    hostname: "https://read.tianheg.org"
  },

  themeConfig: {
    outline: [2, 3],
    sidebar:
    [
      { text: "MAKE：独立创客手册", link: "/make-the-indie-maker-handbook" },
      { text: "狼书Node.js", link: "/langshu-nodejs" },
      { text: "面纱", link: "/the-painted-veil" },
      { text: "月亮与六便士", link: "/the-moon-and-sixpence" },
      { text: "红楼梦", link: "/honglou-meng" },
      { text: "学会如何学习", link: "/learning-how-to-learn" },
      { text: "人的自我寻求", link: "/mans-search-for-himself" },
      { text: "幸福的方法", link: "/happier" },
      { text: "芒格之道", link: "/tao-of-munger" },
      { text: "穷查理宝典", link: "/poor-charlies-almanack" },
      { text: "玄幻小说", link: "/xuanhuan" },
      { text: "哑舍", link: "/yashe" },
      { text: "狂热分子", link: "/true-believer" },
      { text: "操作系统概念", link: "/operating-system-concepts" },
      { text: "操作系统导论", link: "/operating-system-three-easy-pieces" },
      { text: "文化苦旅", link: "/wenhua-kulv" },
      { text: "挽救计划", link: "/project-hail-mary" },
      { text: "小偷家族", link: "/shoplifters" },
      { text: "献给阿尔吉侬的花束", link: "/flowers-for-algernon" },
      { text: "只是为了好玩", link: "/just-for-fun" },
      { text: "索拉里斯星", link: "/solaris" },
      { text: "以鸟兽之名", link: "/yiniaoshou-zhi-ming" },
      { text: "寂寞的游戏", link: "/jimo-de-youxi" },
      { text: "钢铁是怎样炼成的", link: "/how-the-steel-was-tempered" },
      { text: "心理学与生活", link: "/psychology-and-life" },
      { text: "哲学的故事", link: "/story-of-philosophy" },
      { text: "CSS设计的禅意", link: "/the-zen-of-css-design" },
      { text: "窗边的小豆豆", link: "/chuangbian-de-xiaodoudou" },
      { text: "张春桥：1949及以后", link: "/zhang-chunqiao-1949-jiyihou" },
      { text: "高效能人士的七个习惯", link: "/the-7-habits-of-highly-effective-people" },
      { text: "阿西莫夫索引", link: "/asimov" },
      { text: "如何阅读一本书", link: "/how-to-read-a-book" },
      { text: "史蒂夫·乔布斯传", link: "/steve-jobs" },
      { text: "黑客与画家", link: "/hackers-and-painters" },
      { text: "如何成为一名程序员", link: "/how-to-be-a-programmer" },
      { text: "谈美", link: "/tan-mei" },
      { text: "那些忧伤的年轻人", link: "/naxie-youshangde-nianqingren" },
      { text: "查拉图斯特拉如是说", link: "/thus-spoke-zarathustra" },
      { text: "社会心理学", link: "/social-psychology-book" },
      { text: "神曲", link: "/divine-comedy" },
      { text: "道德经", link: "/dao-de-jing" },
      { text: "借我一生", link: "/jiewo-yisheng" },
      { text: "心经", link: "/xinjing" },
      { text: "SICP(JS ver.)", link: "/sicpjs" },
      { text: "醉步男", link: "/zui-bu-nan" },
      { text: "看海的人", link: "/kanhaide-ren" },
      { text: "朝花夕拾", link: "/zhaohua-xishi" },
      { text: "人性的枷锁", link: "/of-human-bondage" },
      { text: "刀锋", link: "/the-razors-edge" },
      { text: "图解HTTP", link: "/tujie-http" },
      { text: "寻欢作乐", link: "/cakes-and-ale" },
      { text: "爱你就像爱生命", link: "/aini-jiuxiang-aishengming" },
      { text: "天生有罪", link: "/born-a-crime" },
      { text: "Web开发JS专业指南", link: "/professional-javascript-for-web-developers" },
      { text: "读书随想录", link: "/the-summing-up" },
      { text: "雪崩", link: "/snow-crash" },
      { text: "极简个性心理学", link: "/making-sence-of-people" },
      { text: "牧羊少年奇幻之旅", link: "/o-alquimista" },
      { text: "爱因斯坦自述", link: "/einstein-himself" },
      { text: "克拉拉与太阳", link: "/klara-and-the-sun" },
      { text: "什锦拼盘", link: "/shijin-pinpan" },
      { text: "拉多之星", link: "/la-duo-zhi-xing" },
      { text: "我生有涯愿无尽：梁漱溟自述文录", link: "/wo-shengyouya-yuanwujin" },
      { text: "时间之书", link: "/shijian-zhi-shu" },
      { text: "未来世界的幸存者", link: "/weilai-shijie-de-xingcunzhe" },
      { text: "三体", link: "/santi" },
      { text: "程序员修炼之道", link: "/the-pragmatic-programmer" },
      { text: "一九八四", link: "/nineteen-eighty-four" },
      { text: "看见", link: "/kanjian" },
      { text: "不迷茫手册", link: "/bumimang-shouce" },
      { text: "恍惚人间", link: "/huanghu-renjian" },
      { text: "过于喧嚣的孤独", link: "/too-loud-a-solitude" },
      { text: "你的第一本哲学书", link: "/what-does-it-all-mean" },
      { text: "遥远的救世主", link: "/yaoyuande-jiushizhu" },
    ],
    socialLinks: [
      { icon: { svg: "<svg xmlns='http://www.w3.org/2000/svg' width='32' height='32' viewBox='0 0 24 24'><path fill='currentColor' d='M18 4H6a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V6a2 2 0 0 0-2-2m-5 14H6v-7h7zm5 0h-3v-7h3zm0-9H6V6h12z'/></svg>" }, link: "https://tianheg.co/", ariaLabel: "Blog" },
      { icon: "github", link: "https://github.com/tianheg/read" },
      { icon: { svg: "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"32\" height=\"32\" viewBox=\"0 0 32 32\"><g fill=\"none\"><path fill=\"url(#vscodeIconsFileTypeVite0)\" d=\"m29.884 6.146l-13.142 23.5a.714.714 0 0 1-1.244.005L2.096 6.148a.714.714 0 0 1 .746-1.057l13.156 2.352a.714.714 0 0 0 .253 0l12.881-2.348a.714.714 0 0 1 .752 1.05z\"/><path fill=\"url(#vscodeIconsFileTypeVite1)\" d=\"M22.264 2.007L12.54 3.912a.357.357 0 0 0-.288.33l-.598 10.104a.357.357 0 0 0 .437.369l2.707-.625a.357.357 0 0 1 .43.42l-.804 3.939a.357.357 0 0 0 .454.413l1.672-.508a.357.357 0 0 1 .454.414l-1.279 6.187c-.08.387.435.598.65.267l.143-.222l7.925-15.815a.357.357 0 0 0-.387-.51l-2.787.537a.357.357 0 0 1-.41-.45l1.818-6.306a.357.357 0 0 0-.412-.45\"/><defs><linearGradient id=\"vscodeIconsFileTypeVite0\" x1=\"6\" x2=\"235\" y1=\"33\" y2=\"344\" gradientTransform=\"translate(1.34 1.894)scale(.07142)\" gradientUnits=\"userSpaceOnUse\"><stop stop-color=\"#41D1FF\"/><stop offset=\"1\" stop-color=\"#BD34FE\"/></linearGradient><linearGradient id=\"vscodeIconsFileTypeVite1\" x1=\"194.651\" x2=\"236.076\" y1=\"8.818\" y2=\"292.989\" gradientTransform=\"translate(1.34 1.894)scale(.07142)\" gradientUnits=\"userSpaceOnUse\"><stop stop-color=\"#FFEA83\"/><stop offset=\".083\" stop-color=\"#FFDD35\"/><stop offset=\"1\" stop-color=\"#FFA800\"/></linearGradient></defs></g></svg>" } , link: "https://vitepress.dev/guide/getting-started", ariaLabel: "VitePress Getting Started" }
    ]
  }
})
